salttesting/mock.py

MagicMock's implementation of mock_open cannot handle iterating over a file without some ugly hackery, so let's just backport the py3's implementation (MagicMock seems to have been incorporated into the py3 standard library at unittest.mock).

backport mock_open from py3 unittest.mock

---

salttesting/runtests.py

Trace:
```
File "/Users/sadams/.pyenv/versions/2.7.9/lib/python2.7/site-packages/salttesting/runtests.py", line 1379, in parse_args
self.colors = get_colors(self.options.no_color is False)
AttributeError: 'Namespace' object has no attribute 'no_color'
```

fixes SaltRuntests 'self.options.no_color' -- should be 'self.options.no_colors'

---

salttesting/runtests.py

Under python 3.4, the unit test loader does some tests on each object in a module to identify test cases.  When the loader tests `RUNTIME_VARS`, the call to `isinstance()` raises an exception because it cannot find the object's `__class__` attribute. See `TestLoader.loadTestsFromModule()` in `unittest/loader.py`.
This change lets `__getattribute__()` find the attributes it inherits fromits base class (`object`).
```
$ python runtests.py -u
[...]
Traceback (most recent call last):
File "runtests.py", line 476, in <module>
main()
File "runtests.py", line 463, in main
status = parser.run_unit_tests()
File "runtests.py", line 431, in run_unit_tests
os.path.join(TEST_DIR, 'unit'), 'Unit', '*_test.py'
File "/home/msteed/salt-testing/salttesting/parser/__init__.py", line 482, in run_suite
tests …
```

Fix py3 failure in RuntimeVars.__getattribute__()

---

salttesting/mock.py

This will allow us to easily skip tests on older mock

Add salttesting.mock.mock_version

---

salttesting/mock.py

Prevents failure when mock is absent, since MagicMock is not defined yet.

Delay assignment of Mock = MagicMock

---

salttesting/jenkins.py

Debian based OS's require the -P option on newer versions of salt. This adds
that functionality to the salt-jenkins-build script.

Added option for pip-based installations

---

salttesting/runtests.py

On MacOS use `tempfile.gettempdir()` rather than `${TMPDIR}` in the test suite.  The latter results in paths that are too long for unix sockets.

salttesting.runtests: TMPDIR on MacOS gives too long paths

---

salttesting/runtests.py

Updates #53.
When logging in as root over `ssh root@host`, `$TMPDIR` and
`tempfile.gettempdir()` are both set to a variation of:
```
/private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/
```
When logging in as root over `sudo -i`, `$TMPDIR` is unset and
`tempfile.gettempdir()` is set to `/tmp`.
My guess is that the second case is an unintended or uncorrected omision
by Apple as they have introduced the longer, randomized temp path in a
recent version of MacOS.

hardcode /tmp on MacOS

---

salttesting/jenkins.py

This lets the salt-jenkins-build pass in the py3 pillar to allow the test suite to run with python3

Add python3 support flag

---

salttesting/parser/__init__.py

salttesting.parser: avoid gettempdir on MacOS

---

salttesting/case.py

@s0undt3ch you may know a better way of doing this, but basically, we never get the right python path when we shell out in python3

python3 compat

---

.gitignore
salttesting/case.py

Windows requires the set command to set environment variables.

Fix PYTHONPATH error in Windows

---

.gitignore
salttesting/case.py

Reverts saltstack/salt-testing#62
@twangboy This was reverted because it was breaking the test suite.

Revert "Fix PYTHONPATH error in Windows"

---

salttesting/case.py

It would appear that popen is not blocking the process return without a pipe.
The communicate() should be doing this, but we might be hitting a bug in popen?
Therefore, set a default timeout as a workaround. The better solution would be to
figure out why we aren't blocking. I have mentioned that as a FIXME.

Set a default timeout for run_script

---

salttesting/jenkins.py

This adds support for `--insecure`. 
Removed an unneeded .replace() from generate_vm_name()

Add insecure flag

---

salttesting/case.py

When running the test suite with Python 3, we need to check for the type of a file path before calling os.remove(). In PY3, os.path.exists() returns true as there are still open file descriptors at this point, but tmp_file.name is an integer instead of a string, causing os.remove to stacktrace.
This change checks for the the tmp_file.name type and closes the file handle.

Check for file path type before calling os.remove()

---

salttesting/case.py

Instead of decoding all of the byte objects in salt's test suite files
Refs the change made in #65 where SpooledTemporaryFiles are read with `w+b` by default. Instead of tracking down all of the places byte strings need to be decoded in Salt proper, let's just do it sooner in salttesting.
An example of `decode()` being used in salt's instegration suite is in https://github.com/saltstack/salt/pull/34990. Many more decodes will be needed throughout that file and this file if we wait to decode. (And that change will need to be reverted in https://github.com/saltstack/salt/pull/34990 if this is merged.)

Let's decode the file read right away

---

salttesting/case.py

Refs #72
When reading in the spooled tmp file, we must decode the binary data immediately. However, we must handle this differently in Py2 and 3. For Py3, we will try to use salt's system encoding dunder if possible, and then fall back to utf-8 for now. In Py2, we're not reading for everything to be unicode yet in Salt, so we'll keep these as string objects until we can make a full switch.
Thanks to @s0undt3ch for the pointers here to not decode straight to ascii inadvertently.

Handle the decode function better when reading in the spooled tmp file

---

salttesting/case.py

This fixes a typo as well as adds the jid to the return (to be used in
some tests I am about to write where I need to check the job cache after
a runner is executed).
I am making similar changes in the run_run_plus func in
tests/integration/__init__.py on the salt repo.

Fix typo in run_run_plus, add fun name and jid to return

---

salttesting/jenkins.py

This PR allow you to spin up a VM that looks exactly like the one Jenkins would use but then it allows you to SSH to it and interact with it.
To use this, you must first have cloud profiles and cloud maps configured. Then, a sample command might be:
`salt-jenkins-build  --cloud-deploy --test-prep-sls=git.salt --vm-source=linode_cent7 --test-interactive -ldebug`
At this point, salt-cloud will request a new VM and bootstrap it with Salt. Once up, it will use salt-ssh to log into the VM and it will use GitFS to pull down the Jenkins states and execute them.
There are a number of TODOs. I'm submitting this PR just as a starting point and it's very incomplete.
* Needs to print out details about the VM after it's provisioned. Right now you have to search through the logs a bit to find the IP …

Interactive support

---

salttesting/case.py

Instead, compile output by executing salt.output.display_output() on the
return data obtained from executing the runner via the Python API.

Don't execute the runner twice in run_run_plus

---

salttesting/helpers.py

* Check for unknown processes and handle that condition
* Modify the shutdown routine to be more aggressive. By the time we hit this, we have already been through several iterations of trying to signal the process nicely. There is no sense at this point in trying to do anything but send SIGTERM. So, now we do so immediately and retry up to twice more. We also check to ensure that we do not attempt to kill ourselves or the logger for the runtests script, since this will stacktrace and cause unpredicitable behavior, including possible failures to exit or inconsistent logging.

Change signal handling on cleanup

---

salttesting/case.py

We were in a constant loop polling and calculating the time. Tracing the process showed constant stats of `/etc/localtime`.  It was driving the test runner to consume all the CPU power.
By adding a small sleep, I decreased the test time for salt module from 27 minutes to about four and a half.

Fix major performance issue

---

salttesting/jenkins.py

- Wait for salt package download on parallels: when the network is congested, the download outlasts salt's timeout somehow, so rather than fail the test run, check the download hash until it matches.
- allow branch info from other GitHub accounts: such as `jfindlay:mac_branch`.  This is useful for setting up custom jenkins test runs against unofficial branches to allow more integrated testing of changes before needing to merge the changes into the official repo.
- use `status` rather than `state` saltstack/salt#36166

more parallels fixes and enhancements

---

salttesting/parser/__init__.py

This provides the groundwork for allowing users to maintain their own test infrastructure and leverage salt-testing to do all of the acceptance testing for their salt states and modules.

Discover ext dirs

---

salttesting/unit.py

This will nuke and pave changes between test classes.
We've had a lot of problems with tests changing the test environment and not cleaning up after themselves. This gives us a centralized location to put items which should always be put back to sane defaults after a test class runs.

Create a force-reset method

---

salttesting/parser/__init__.py

I made an error in 772b8e0. This correctly sets the loader path.
Fixes an issue where the shell tests would bail out.

Fix logic error in path detection

---

salttesting/unit.py

This will save ~10% on the total test run time. We can turn it back on if it becomes needed again.

Default not to show process info

---

salttesting/jenkins.py

Needed to be able to install both `salttesting==2016.9.7` and `git+https://github.com/saltstack/salt-testing@develop#egg=SaltTesting` formats.
Related: saltstack/salt-jenkins#257

Update option to use full namespec offered by pip for SaltTesting installs

---

salttesting/case.py

In #73 we introduced a check against the python version.
It's supposed to return true only for versions that are 3.x or above but instead it returns true for  2.x.
ex for Python 2.7.12:
```
>>> sys.version_info > (2,)
True
>>> sys.version_info > (3,)
False
```
This bug that this fixes breaks Unicode handling for many cases where a test uses a shell and gets Unicode in the response.

Fix incorrect version comparison

---

salttesting/unit.py

This should not be necessary here.

Remove super

---

salttesting/case.py

This PR fixes crashes if using Python 2.6 version.
These errors occurs because `sys.version_info` returns a tuple in Python 2.6.
Doc: https://docs.python.org/2/library/sys.html#sys.version_info

Prevent crashes if Python version < 2.7

---

salttesting/jenkins.py

Adds two parameters:
- `--windows` to designate that this is a Windows minion
- `--update-winrepo` to update the winrepo on the master for the pkg tests and some of the setup states
When the `--windows` switch is passed it will:
- Use winexe in place of ssh
- Use SMB to copy artifacts back to the slave
Adds a reboot after the minion is installed in order for the `salt-call` commands to run.

Tests on Windows with Jenkins

---

salttesting/mock.py

This PR fixes an issue in a python version comparison when backporting python 3 `unittest.mock` library for `mock_open`.
The current comparison does not backport `mock_open` from python 3 when using version 2.x. This produces issues running unit tests in such python version because the lack of `read`, `readlines` and other related method in the provided `mock_open`.

Fix bad logic for "mock_open" in python 2.x versions

---

salttesting/case.py

This echoes changes made in https://github.com/saltstack/salt/pull/39646.
Now that string kwargs are no longer supported, an alternate way was needed for passing arguments to remote execution functions which accept arguments with names already used in ``integration.ModuleCase.run_function()`` (i.e.  ``arg``, ``timeout``).

Add substitute kwargs to get around shadowing in integration.ModuleCase.run_function()
